webtalk_init -webtalk_dir /home/parallels/Documents/canny-zybo-z7/Zybo-Z7-20-pcam-5c-2019.1/vivado_proj/Zybo-Z7-20-pcam-5c.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-02-16 04:52:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2865rq1npsmm1h6tppdg0htheu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.202 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1645015872000" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1645015872000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1645015962724"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1645015962724"
webtalk_transmit -clientid 2128839028 -regid "" -xml /home/parallels/Documents/canny-zybo-z7/Zybo-Z7-20-pcam-5c-2019.1/vivado_proj/Zybo-Z7-20-pcam-5c.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/parallels/Documents/canny-zybo-z7/Zybo-Z7-20-pcam-5c-2019.1/vivado_proj/Zybo-Z7-20-pcam-5c.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/parallels/Documents/canny-zybo-z7/Zybo-Z7-20-pcam-5c-2019.1/vivado_proj/Zybo-Z7-20-pcam-5c.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
